version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12

    working_directory: /go/src/github.com/hexlabsio/inventory-account-splitter

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-pkg-cache

      - run: 
          name: Go Get
          command: |
            go get github.com/aws/aws-lambda-go/lambda
            go get github.com/aws/aws-lambda-go/events

      - save_cache:
          key: v1-pkg-cache
          paths:
          - "/go/pkg"

      - run:
          name: Test
          command: go test

      - run:
          name: Build
          command: GOOS=linux go build handler.go && zip handler.zip ./handler

      - run:
          name: Download KloudFormation
          command:  curl -sSL install.kloudformation.hexlabs.io | bash -s -- -local
      
      - restore_cache:
          keys:
            - kloudformation-{{ checksum "kloudformation.sh" }}

      - run:
          name: Deploy Stack
          command:  ./kloudformation.sh deploy -stack-name inventory-account-splitter -m serverless@0.1.13 -bucket hexlabs-deployments -location handler.zip -output outputs.properties

      - store_artifacts:
          path: template.yml

      - store_artifacts:
          path: outputs.properties

      - save_cache:
          paths:
            - ~/.kloudformation
          key: kloudformation-{{ checksum "kloudformation.sh" }}